### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by minhnimble** [iamdarqueza/nimsurvey#3]
You did have some interesting choices for the UI implementations. At the same time, there are some noticeable issues with the current implementation and I would like to list them down as follow:

- On the Launch screen:

When first starting the application, there is no launch screen and the application shows as a blank white page.

https://user-images.githubusercontent.com/70877098/158937912-3393d7a9-08f5-4b15-abdf-e151815d8c57.MP4

- On the Login screen:

  1. The current status bar color is hard to see with the dark navigation bar and dark content below.
  2. The keyboard with the top toolbar partially covers the Login button and make it hard for users to input their credentials in one go. Maybe we can handle to move the textfields and the button up a little bit more while the keyboard is active. What do you think?
  <img src="https://user-images.githubusercontent.com/70877098/158937255-fc7cd422-9803-413d-9442-d59dd0d4bb9e.png" width="300">

  3. As you can see from the above image, the tint color of the textfields are default to blue. What do you think about setting it to white for matching our design?
  4. There is no loading indicator for showing the animated progress, the screen just fade out during the API call time.
    <img src="https://user-images.githubusercontent.com/70877098/158937658-1dd08003-bcda-40b4-86d4-cba98cfda9a1.png" width="300">

  5. When providing an invalid email format string into the email textfield, the Login button is still enabled and thus the login API still gets called and it always results in an error message. What is your opinion on checking for the validity of the email before calling the API as well?
  <img src="https://user-images.githubusercontent.com/70877098/158937530-c09c81e0-5ea7-4b6e-8672-b8eff7364732.png" width="300">

- On the Survey List screen:

I am unable to verify this screen at this point. As a result, I will check later on after you fixed the Login problem #2 🙏

**Comment by iamdarqueza** [comment]
Hi. Issues has been resolved, I've pushed a new build for UI issues
