### ISSUE TITLE
Testing issues

### ISSUE THREAD

**Issue by minhnimble** [iamdarqueza/nimsurvey#5]
Unfortunately, right now I don't see you implement any unit test for the application. I am wondering if you have any experience in writing unit tests and would you consider creating some tests for the application on the logic part?

Apart from that, I also see that you don't include any UI tests in the application. Can you add a few UI tests with some basic flow in the application? An example could be a simple flow to open the Survey Lists screen from Login screen. 🙏

**Comment by iamdarqueza** [comment]
Hi. I've wrote some unit test for the login screen. Thank you
